name = "cat_api"
version = "1.0.0"
description = "A cat photo API written in Gleam"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
wisp = ">= 1.5.3 and < 2.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"
mist = ">= 4.0.6 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 1.6.5 and < 2.0.0"
